### ISSUE TITLE
Branding - Logo / Website

### ISSUE THREAD

**Issue by skorfmann** [cdk-dev/base#5]
We should get some kind of logo, the current one doesn't work very well in my opinion.

![Screenshot 2020-07-26 at 23 10 00](https://user-images.githubusercontent.com/136789/89713746-0cbb1680-d99a-11ea-84fe-d899b11e6cdb.png)

**Comment by skorfmann** [comment]
Some nice open graph images would also be cool :)

**Comment by skorfmann** [comment]
This is a proposal by @aripalo extracted from a design uploaded in Slack

Logo:

![Screenshot 2020-09-02 at 16 03 20](https://user-images.githubusercontent.com/136789/91993597-da50cf00-ed35-11ea-9193-14c0f08f2608.png)

Landing Page

![homepage-temp-v20200828-v1830](https://user-images.githubusercontent.com/136789/91993618-e472cd80-ed35-11ea-9fe6-627186c3e10f.png)

**Comment by mbonig** [comment]
Love it

**Comment by mbonig** [comment]
If you can point me at the source graphics I can get this incorporated.

**Comment by skorfmann** [comment]
New website is live https://github.com/cdk-dev/website/pull/10

Logo was spontaneously added by @EdwinRad 
![image](https://user-images.githubusercontent.com/136789/94474213-9b475980-01cd-11eb-9a07-939058fd0b81.png)
